In [2]:
import numpy as np

##Problem 1: Array Creation


1. Initialize an empty array with size 2X2

In [15]:

empty_array = np.empty((2, 2))
print(empty_array)

[[3.09287140e-316 0.00000000e+000]
 [6.68546084e-310 5.33196831e-317]]


 2. Initialize an all one array with size 4X2

In [17]:

ones_array = np.ones((4, 2))
print (ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value

In [16]:

filled_array = np.full((3, 3), 7, dtype=int)
print (filled_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array

In [18]:

a = np.array([1, 2, 3])
zeros_like_array = np.zeros_like(a)
print (zeros_like_array)

[0 0 0]


5. Return a new array of ones with same shape and type as a given array

In [19]:

ones_like_array = np.ones_like(a)
print (ones_like_array)

[1 1 1]


6. For an existing list new_list = [1,2,3,4] convert to a numpy array

In [20]:

new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print (numpy_array)

[1 2 3 4]



# Problem - 2: Array Manipulation

 1. Create an array with values ranging from 10 to 49

In [21]:

range_array = np.arange(10, 50)
print (range_array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8

In [22]:

matrix_3x3 = np.arange(9).reshape(3, 3)
print (matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix

In [24]:

identity_matrix = np.eye(3)
print (identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array

In [14]:

random_array = np.random.random(30)
print(random_array)
mean_value = random_array.mean()
print(mean_value)


[0.15350754 0.18220761 0.00590308 0.00790909 0.47254011 0.92915856
 0.21044887 0.02045696 0.64681278 0.02207773 0.42620474 0.74558297
 0.38887518 0.5420514  0.95812395 0.86185236 0.78747771 0.49816902
 0.48693753 0.12129499 0.6382022  0.29165984 0.36506982 0.38376439
 0.96696873 0.72593736 0.20802928 0.00583701 0.8306067  0.96774449]
0.46171373299180735


5. Create a 10X10 array with random values and find the minimum and maximum values

In [26]:

random_array_10x10 = np.random.random((10, 10))
min_value = random_array_10x10.min()
max_value = random_array_10x10.max()
print(min_value)
print(max_value)

0.0012271407665656042
0.9968107343442866


 6. Create a zero array of size 10 and replace 5th element with 1

In [27]:

zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0]

In [28]:

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print (reversed_arr)

[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside

In [30]:

array_2d = np.ones((5, 5))
array_2d[1:-1, 1:-1] = 0
print (array_2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


 9. Create an 8X8 matrix and fill it with a checkerboard pattern

In [29]:

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print (checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]



# Problem - 3: Array Operations

In [31]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [33]:
sum_array = x + y
print (sum_array)

[[ 6  8]
 [10 13]]


In [34]:
diff_array = x - y
print(diff_array)

[[-4 -4]
 [-4 -3]]


In [36]:
multiplied_array = x * 3
print(multiplied_array)

[[ 3  6]
 [ 9 15]]


In [37]:
squared_array = x**2
print(squared_array)

[[ 1  4]
 [ 9 25]]


In [38]:
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print(dot_vw)
print(dot_xv)
print(dot_xy)

219
[29 77]
[[19 22]
 [50 58]]


In [39]:
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)
print(concat_xy_row)
print(concat_vw_col)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


In [40]:
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError:
    # If shapes are incompatible, reshape v
    concat_xv = np.concatenate((x, v.reshape(1, -1)), axis=0)
print(concat_xv)


[[ 1  2]
 [ 3  5]
 [ 9 10]]


# Problem - 4: Matrix Operations

 1. Prove A.A^-1 = I

In [41]:
A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("A.A^-1:\n", I)

A.A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB != BA

In [42]:
B = np.array([[5, 3], [2, 1]])
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("\nBA:\n", BA)


AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]


 3. Prove (AB)^T = B^T A^T

In [43]:
AB_transpose = AB.T
B_transpose_A_transpose = np.dot(B.T, A.T)
print("\n(AB)^T:\n", AB_transpose)
print("\nB^T A^T:\n", B_transpose_A_transpose)


(AB)^T:
 [[23 51]
 [13 29]]

B^T A^T:
 [[23 51]
 [13 29]]


 Solving the system of linear equations using inverse methods

In [44]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
X = np.linalg.solve(A, B)
print("\nSolution using np.linalg.solve:\n", X)



Solution using np.linalg.solve:
 [ 2.  1. -2.]


Solving using np.linalg.inv

In [45]:
X_inv_method = np.dot(np.linalg.inv(A), B)
print("\nSolution using np.linalg.inv:\n", X_inv_method)


Solution using np.linalg.inv:
 [ 2.  1. -2.]


# 10.2 Experiment: How Fast is NumPy?

In [46]:
import time

In [47]:
def elementwise_addition_list(n):
    list1 = list(range(n))
    list2 = list(range(n))
    start_time = time.time()
    result = [x + y for x, y in zip(list1, list2)]
    end_time = time.time()
    return end_time - start_time

def elementwise_addition_numpy(n):
    arr1 = np.arange(n)
    arr2 = np.arange(n)
    start_time = time.time()
    result = arr1 + arr2
    end_time = time.time()
    return end_time - start_time

def elementwise_multiplication_list(n):
    list1 = list(range(n))
    list2 = list(range(n))
    start_time = time.time()
    result = [x * y for x, y in zip(list1, list2)]
    end_time = time.time()
    return end_time - start_time

def elementwise_multiplication_numpy(n):
    arr1 = np.arange(n)
    arr2 = np.arange(n)
    start_time = time.time()
    result = arr1 * arr2
    end_time = time.time()
    return end_time - start_time

def dot_product_list(n):
    list1 = list(range(n))
    list2 = list(range(n))
    start_time = time.time()
    result = sum(x * y for x, y in zip(list1, list2))
    end_time = time.time()
    return end_time - start_time

def dot_product_numpy(n):
    arr1 = np.arange(n)
    arr2 = np.arange(n)
    start_time = time.time()
    result = np.dot(arr1, arr2)
    end_time = time.time()
    return end_time - start_time

def matrix_multiplication_list(n):
    matrix1 = [[1] * n for _ in range(n)]
    matrix2 = [[2] * n for _ in range(n)]
    start_time = time.time()
    result = [[sum(a * b for a, b in zip(row_a, col_b))
               for col_b in zip(*matrix2)] for row_a in matrix1]
    end_time = time.time()
    return end_time - start_time

def matrix_multiplication_numpy(n):
    matrix1 = np.ones((n, n))
    matrix2 = np.ones((n, n)) * 2
    start_time = time.time()
    result = np.dot(matrix1, matrix2)
    end_time = time.time()
    return end_time - start_time

n = 1000000
list_add_time = elementwise_addition_list(n)
numpy_add_time = elementwise_addition_numpy(n)
list_mult_time = elementwise_multiplication_list(n)
numpy_mult_time = elementwise_multiplication_numpy(n)
list_dot_time = dot_product_list(n)
numpy_dot_time = dot_product_numpy(n)

matrix_size = 1000
list_matrix_mult_time = matrix_multiplication_list(matrix_size)
numpy_matrix_mult_time = matrix_multiplication_numpy(matrix_size)

print("\nPerformance Comparison:")
print("Element-wise Addition (List):", list_add_time, "seconds")
print("Element-wise Addition (NumPy):", numpy_add_time, "seconds")
print("Element-wise Multiplication (List):", list_mult_time, "seconds")
print("Element-wise Multiplication (NumPy):", numpy_mult_time, "seconds")
print("Dot Product (List):", list_dot_time, "seconds")
print("Dot Product (NumPy):", numpy_dot_time, "seconds")
print("Matrix Multiplication (List):", list_matrix_mult_time, "seconds")
print("Matrix Multiplication (NumPy):", numpy_matrix_mult_time, "seconds")


Performance Comparison:
Element-wise Addition (List): 0.151444673538208 seconds
Element-wise Addition (NumPy): 0.011269807815551758 seconds
Element-wise Multiplication (List): 0.13126683235168457 seconds
Element-wise Multiplication (NumPy): 0.010020732879638672 seconds
Dot Product (List): 0.08490729331970215 seconds
Dot Product (NumPy): 0.00247955322265625 seconds
Matrix Multiplication (List): 83.6282844543457 seconds
Matrix Multiplication (NumPy): 0.07018113136291504 seconds
